Jargons/Jargons/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls'))
]

Jargons/dashboard/urls.py
from django.urls import path
from dashboard import views

# TEMPLATE TAGGING
app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload, name='upload'),
    path('indices/', views.indices, name='indices'),
    path('predict/', views.get_prediction, name='predict')
]

Jargons/dashboard/models.py
from django.db import models


class UserProfile(models.Model):

    employee_id = models.IntegerField(unique=True, primary_key=True)
    password = models.CharField(max_length=256)

    def __str__(self):
        return str(self.employee_id)

Jargons/dashboard/forms.py
from django import forms
from dashboard.models import UserProfile


class UserForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('employee_id', 'password')

Jargons/dashboard/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.core.files.storage import FileSystemStorage
from django.urls.base import reverse
from django.contrib import messages
from django.shortcuts import render
import dashboard.Elastic as elastic
from django.views.decorators.csrf import csrf_exempt
import dashboard.prediction as prediction


def index(request):
    message = None
    for msg in messages.get_messages(request):
        message = msg
        break
    return render(request, 'dashboard/home.html', {'message': message})


def upload(request):
    if request.method == "POST":
        try:
            url = "/api/v2/containers/"
            context = {}
            uploaded_file = request.FILES['csv-file']
            fs = FileSystemStorage()
            name = fs.save(uploaded_file.name, uploaded_file)
            print(name)
            context['url'] = fs.url(name)

            elastic.csv_writer(fs.path(name), str(name).split('.')[0].lower(), 'data', ';')
            fs.delete(name)
            messages.add_message(request, messages.INFO, 'File uploaded successfully')
            return HttpResponseRedirect(reverse('dashboard:index'))
        except Exception as e:
            print(e)
            messages.add_message(request, messages.INFO, 'Failed to upload file...!')
            return HttpResponseRedirect(reverse('dashboard:index'))

    message = None
    for msg in messages.get_messages(request):
        message = msg
        break
    return render(request, 'dashboard/home.html', {'message': message})


def indices(request):
    if request.method == 'GET':
        indices = list(elastic.get_indices())
        print('indices', indices)
        return JsonResponse({'indices': indices})

    return JsonResponse({})


@csrf_exempt
def get_prediction(request):
    if request.method == 'POST':
        index_name = request.POST.get('index')
        print(index_name)
        data = dict()
        predictions, test = prediction.predict(index_name)

        y_predict = list()
        for p in predictions:
            y_predict.append(p.tolist()[0])

        y_test = list()
        for t in test:
            y_test.append(t.tolist()[0])

        data['prediction'] = {
            'x': list(range(len(y_predict))),
            'y': y_predict
        }
        data['test'] = {
            'x': list(range(len(y_test))),
            'y': y_test
        }
        print(data)
        return JsonResponse(dict(data))

    return JsonResponse({})

Jargons/templates/dashboard/home.html
<!DOCTYPE html>
{% extends 'dashboard/home_base.html' %}

{% load staticfiles %}

{% block head %}
    <title>Dashboard</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .lds-ring {
            display: inline-block;
            position: relative;
            width: 1.5em;
            height: 1.5em;
        }

        .lds-ring div {
            box-sizing: border-box;
            display: block;
            position: absolute;
            width: 1.3em;
            height: 1.3em;
            margin: .1em;
            border: .2em solid dodgerblue;
            border-radius: 50%;
            animation: lds-ring 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;
            border-color: dodgerblue transparent transparent transparent;
        }

        .lds-ring div:nth-child(1) {
            animation-delay: -0.45s;
        }

        .lds-ring div:nth-child(2) {
            animation-delay: -0.3s;
        }

        .lds-ring div:nth-child(3) {
            animation-delay: -0.15s;
        }

        @keyframes lds-ring {
            0% {
                transform: rotate(0deg);
            }
            100% {
                transform: rotate(360deg);
            }
        }

        .card .table td, .card .table th {
            padding-right: 0rem;
            padding-left: 0rem;
        }

        a:hover {
            cursor: pointer;
        }

        .ct-series-a .ct-point {
            stroke: blue;
            stroke-width: 5px;
        }
        .ct-series-b .ct-point {
            stroke: black;
            stroke-width: 5px;
        }
        .ct-series-a .ct-line {
            stroke: blue;
            stroke-width: 2px;
        }
        .ct-series-b .ct-line {
            stroke: black;
            stroke-width: 2px;
        }
    </style>
{% endblock %}

{% block page_name %}Containers{% endblock %}

{% block body %}
    <!-- Main content -->
    <div class="main-content">
        <!-- Top navbar -->
        <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
            <div class="container-fluid">
                <!-- Brand -->
                <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="{% url 'dashboard:index' %}">Dashboard</a>
            </div>
        </nav>
        <!-- Header -->
        <div class="header bg-gradient-primary pb-8 pt-5 pt-md-6">
            {% if message %}
                <p class="lead text-center text-white">{{ message }}</p>
            {% endif %}
            <div class="container-fluid">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#createcontainer"
                        id="modal_btn">
                    <span class="btn-inner--icon"><i class="fa fa-plus-circle"></i></span>
                    <span class="btn-inner--text">Import CSV File</span>
                </button>
                <button type="button" class="btn btn-secondary">
                    <span class="btn-inner--icon"><i class="fa fa-line-chart"></i></span>
                    <span class="btn-inner--text">Select graph</span>
                    <span class="dropdown">
                        <select name="indices" id="indices" onchange="predict(this)">
                            <option disabled selected>Select...</option>
                        </select>
                    </span>
                </button>
                <!-- Modal -->
                <div class="modal fade" id="createcontainer" tabindex="-1" role="dialog"
                     aria-labelledby="createcontainerLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <form id="file_details" method="post" action={% url 'dashboard:upload' %} enctype="multipart/form-data">
                                <div class="modal-body">
                                    <div class="mb-3">
                                        <large class="text-uppercase font-weight-bold">Select a file</large>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input type="file" class="form-control" id="csv-file" name="csv-file"
                                                   oninput="check_file(this)" required>
                                            <small class="" id="file_label"></small>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" id="upload_btn" class="btn btn-primary" onclick="upload()">Upload
                                    </button>
                                    <div id="loader" class="lds-ring" style="display: none">
                                        <div></div>
                                        <div></div>
                                        <div></div>
                                        <div></div>
                                    </div>
                                    <button type="button" id="cancel_btn" class="btn btn-secondary ml-auto"
                                            data-dismiss="modal">Close
                                    </button>
                                </div>
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page content -->
        <div class="container-fluid mt--7">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-chart" style="height: auto">
                        <div class="card-header">
                            <h2 class="card-title">Record</h2>
                            <span class="form-group"><input type="checkbox" id="predicted" onchange="update_graph()" disabled checked>
                                Predicted
                            </span>
                            <span class="form-group"><input type="checkbox" id="actual" onchange="update_graph()" disabled checked>
                                Actual
                            </span>
                            <span id="graph_loader" class="lds-ring float-right" style="display: none">
                                <div></div>
                                <div></div>
                                <div></div>
                                <div></div>
                            </span>
                        </div>
                        <div class="card-body">
                            <div class="records ct-perfect-fourth" style="padding: 10%;height: 400px;"></div>
                        </div>
                    </div>
                </div>
                <div id="chart_div" style="width: 900px; height: 500px;"></div>
            </div>
        </div>
    </div>


{% endblock %}
{% block script %}

    <script type="text/javascript">

    loadIndices();
    var x_predict, y_predict, y_test;

    function upload() {
        document.getElementById('upload_btn').innerText = 'Uploading...';
        document.getElementById('cancel_btn').disabled = true;
        document.getElementById('loader').style.display = 'block';
    }

    function loadIndices() {
        $.ajax({
            type: 'GET',
            url: '{% url 'dashboard:indices' %}',
            success: function (data) {
                console.log(data);
                {#document.getElementById('indices').innerHTML = "";#}
                data = data['indices'];
                for (var i in data) {
                    $('#indices').append("<option>" + data[i] + "</option>")
                }
                {#document.getElementById(data[0]).checked = true;#}
            },
            error: function (data) {
                console.log(data);
                alert("Something went wrong!");
            }
        });
    }

    function predict() {
        document.getElementById('graph_loader').style.display = 'block';
        console.log(document.getElementById('indices').value);
        document.getElementById('predicted').disabled = false;
        document.getElementById('actual').disabled = false;

        data = {'index': document.getElementById('indices').value};
        $.ajax({
            type: 'POST',
            url: '{% url 'dashboard:predict' %}',
            data: data,
            success: function (data) {
                console.log(data);
                x_predict = data['prediction']['x'];
                y_predict = data['prediction']['y'];
                y_test = data['test']['y'];
                update_graph();
            },
            error: function (data) {
                console.log(data);
                alert("Something went wrong!");
            }
        });
    }

    function drawChart(x, y, low, high) {
        document.getElementById('graph_loader').style.display = 'none';
        new Chartist.Line('.records', {
            labels: x,
            series: y
        }, {
            stretch: true,
            showLine: false,
            lineSmooth: false,
            axisX: {
                showGrid: false,
                showLabel: true,
                labelInterpolationFnc: function(value, index) {
                    return index % 150 === 0 ? value : null;
                }
            },
            axisY: {
                showGrid: false,
                low: low,
                high: high
            }
        },
        {
            axisX: {
                labelInterpolationFnc: function (value, index) {
                    return index % 40 === 0 ? value : null;
                }
            }
        });
    }

    function update_graph(){
        var y = [];
        var low, high;
        if(document.getElementById('predicted').checked){
            y = [y_predict];
            low = undefined;
            high = undefined;
        }
        if(document.getElementById('actual').checked){
            y = [[], y_test];
            low = -1.5;
            high = 1.5;
        }
        if(document.getElementById('predicted').checked && document.getElementById('actual').checked){
            y = [y_predict, y_test];
            low = -1.5;
            high = 1.5;
        }
        drawChart(x_predict, y, low, high);
    }

    function check_file(element) {
        console.log(element.value);
        document.getElementById('upload_btn').disabled = false;
    }
    </script>

{% endblock %}

Jargons/templates/dashboard/home_base.html
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Chart CSS Files -->
    <link href="{% static 'dashboard/assets/vendor/chart.js/dist/chartist.css' %}" rel="stylesheet">
    {% block head %}{% endblock %}

    <!-- Favicon -->
    <link href="{% static 'dashboard/assets/img/brand/favicon.png' %}" rel="icon" type="image/png">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- Icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="{% static 'dashboard/assets/vendor/nucleo/css/nucleo.css' %}" rel="stylesheet">
    <link href="{% static 'dashboard/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <!-- Argon CSS -->
    <link type="text/css" href="{% static 'dashboard/assets/css/argon.css' %}?v=1.0.0" rel="stylesheet">

{#    <link href="{% static 'dashboard/assets/vendor/chart.js/dist/chartist.min.css' %}" rel="stylesheet">#}
</head>

<body>

{% block body %}{% endblock %}

<!-- Argon Scripts -->
<!-- Core -->
<script src="{% static 'dashboard/assets/vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'dashboard/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<!-- Optional JS -->
<script src="{% static 'dashboard/assets/vendor/chart.js/dist/Chart.min.js' %}"></script>
<script src="{% static 'dashboard/assets/vendor/chart.js/dist/Chart.extension.js' %}"></script>
<script src="{% static 'dashboard/assets/vendor/chart.js/dist/Chart.min.js' %}"></script>
<script src="{% static 'dashboard/assets/vendor/chart.js/dist/chartist.min.js' %}"></script>
<script src="{% static 'dashboard/assets/vendor/chart.js/dist/chartist.js' %}"></script>
<!-- Argon JS -->
<script src="{% static 'dashboard/assets/js/argon.js' %}?v=1.0.0"></script>

{% block script %}{% endblock %}

</body>
</html>

Jargons/templates/dashboard/index.html
<!DOCTYPE html>
{% extends 'dashboard/login_base.html' %}

{% load staticfiles %}

{% block head %}
    <title>Jargons - A Web App For Private Virtual Server</title>
{% endblock %}

{% block body %}
    <header class="header-global">
        <nav id="navbar-main" class="navbar navbar-main navbar-expand-lg navbar-transparent navbar-light headroom">
            <div class="container">
                <a class="navbar-brand pt-0" style="font-size: 1.25rem" href="{% url 'dashboard:index' %}">
                    <img src="{% static 'dashboard/assets/img/brand/favicon.png' %}">
                    <span class="btn-inner--text text-blue">Coding Container</span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse" id="navbar_global">
                    <div class="navbar-collapse-header">
                        <div class="row">
                            <div class="col-6 collapse-brand">
                                <a class="pt-0" style="font-size: 1.25rem" href="{% url 'dashboard:index' %}">
                                    <img src="{% static 'dashboard/assets/img/brand/favicon.png' %}">
                                    <span class="btn-inner--text text-blue">Coding Container</span>
                                </a>
                            </div>
                            <div class="col-6 collapse-close">
                                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                                    <span></span>
                                    <span></span>
                                </button>
                            </div>
                        </div>
                    </div>
                    <ul class="navbar-nav align-items-lg-center ml-lg-auto">
                        {% if loggedIn %}
                            <li class="nav-item nav-link-icon" data-toggle="tooltip">
                                <a href="{% url 'dashboard:dashboard' %}" class="btn btn-outline-neutral">
                                    <span class="nav-link-inner--text">Dashboard</span>
                                </a>
                            </li>
                            <li class="nav-item nav-link-icon" data-toggle="tooltip">
                                <a href="{% url 'dashboard:logout' %}" class="btn btn-neutral">
                                    <span class="nav-link-inner--text">Log out</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item  nav-link-icon" data-toggle="tooltip">
                                <a href="{% url 'dashboard:login' %}" class="btn btn-outline-neutral">
                                    <span class="nav-link-inner--text">Sign in</span>
                                </a>
                            </li>
                            <li class="nav-item nav-link-icon" data-toggle="tooltip">
                                <a href="{% url 'dashboard:register' %}" class="btn btn-neutral">
                                    <span class="nav-link-inner--text">Sign up</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="position-relative">
            <!-- shape Hero -->
            <section class="section section-lg section-shaped pb-250">
                <div class="shape shape-style-1 shape-default">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                {% if message %}
                    <p class="lead text-center text-white">{{ message }}</p>
                {% endif %}
                <div class="container py-lg-md d-flex">
                    <div class="col px-0">
                        <div class="row">
                            <div class="col-lg-12">
                                <h1 class="display-3  text-white">Ready to start coding with Coding Container?
                                    <span>with pre-built coding environment</span>
                                </h1>
{#                                <p class="lead  text-white">The design system comes with four pre-built pages to help you#}
{#                                    get started faster. You can change the text and images and you're good to go.</p>#}
                            </div>
                        </div>
                    </div>
                </div>
                <!-- SVG separator -->
                <div class="separator separator-bottom separator-skew">
                    <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1"
                         xmlns="http://www.w3.org/2000/svg">
                        <polygon class="fill-white" points="2560 0 2560 100 0 100"></polygon>
                    </svg>
                </div>
            </section>
            <!-- 1st Hero Variation -->
        </div>
        <section class="section section-lg pt-lg-0 mt--200">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="row row-grid">
                            <div class="col-lg-4">
                                <div class="card card-lift--hover shadow border-0">
                                    <div class="card-body py-5">
                                        <div class="icon icon-shape icon-shape-primary rounded-circle mb-4">
                                            <i class="fa fa-edit"></i>
                                        </div>
                                        <h6 class="text-primary text-uppercase">Editor</h6>
                                        <p class="description mt-3">With the amazing editor in Codeanywhere,
                                            you will forget you ever used any other code editor.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="card card-lift--hover shadow border-0">
                                    <div class="card-body py-5">
                                        <div class="icon icon-shape icon-shape-success rounded-circle mb-4">
                                            <i class="ni ni-controller"></i>
                                        </div>
                                        <h6 class="text-success text-uppercase">Remote Connection</h6>
                                        <p class="description mt-3">Edit your code remotely wherever it is; FTP, SFTP,
                                            even Dropbox or Google Drive and more.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="card card-lift--hover shadow border-0">
                                    <div class="card-body py-5">
                                        <div class="icon icon-shape icon-shape-warning rounded-circle mb-4">
                                            <i class="fa fa-terminal"></i>
                                        </div>
                                        <h6 class="text-warning text-uppercase">Terminal console</h6>
                                        <p class="description mt-3">Use built-in terminal console to run any command on
                                            your Container or even remote servers (using SSH).</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock %}

Jargons/templates/dashboard/login.html
<!DOCTYPE html>
{% extends 'dashboard/login_base.html' %}

{% load staticfiles %}

{% block head %}
    <title>Login</title>
{% endblock %}

{% block body %}

<header class="header-global">
    <nav id="navbar-main" class="navbar navbar-main navbar-expand-lg navbar-transparent navbar-light headroom">
        <div class="container">
            <a class="navbar-brand pt-0" style="font-size: 1.25rem" href="{% url 'dashboard:index' %}">
                <img src="{% static 'dashboard/assets/img/brand/favicon.png' %}">
                <span class="btn-inner--text text-blue">Coding Container</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global"
                    aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbar_global">
                <div class="navbar-collapse-header">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <a class="pt-0" style="font-size: 1.25rem" href="{% url 'dashboard:index' %}">
                                <img src="{% static 'dashboard/assets/img/brand/favicon.png' %}">
                                <span class="btn-inner--text text-blue">Coding Container</span>
                            </a>
                        </div>
                        <div class="col-6 collapse-close">
                            <button type="button" class="navbar-toggler" data-toggle="collapse"
                                    data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false"
                                    aria-label="Toggle navigation">
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
<main>
    <section class="section section-shaped section-lg">
        <div class="shape shape-style-1 bg-gradient-default">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
        {% if message %}
            <p class="lead text-center text-white">{{ message }}</p>
        {% endif %}
        <div class="container pt-lg-md">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card bg-secondary shadow border-0">
                        <div class="card-body px-lg-5 py-lg-5">
                            <div class="text-center display-4 mb-4">
                                <large>Sign In With Credentials</large>
                            </div>
                            <form role="form" method="post">
                                <div class="form-group">
                                    <div class="input-group input-group-alternative mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                                        </div>
                                        <input class="form-control" placeholder="employee ID" type="number" name="employee_id" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group input-group-alternative">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                                        </div>
                                        <input class="form-control" placeholder="Password" type="password" name="password" required>
                                    </div>
                                </div>
{#                                <div class="custom-control custom-control-alternative custom-checkbox">#}
{#                                    <input class="custom-control-input" id=" customCheckLogin" type="checkbox">#}
{#                                    <label class="custom-control-label" for=" customCheckLogin">#}
{#                                        <span>Remember me</span>#}
{#                                    </label>#}
{#                                </div>#}
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary my-4">Sign in</button>
                                </div>
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-6">
                            <a href="#" class="text-light">
{#                                <small>Forgot password?</small>#}
                            </a>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{% url 'dashboard:register' %}" class="text-light">
                                <small>Create new account</small>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}